[package]
name = "rust-nlp100"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "1_0"
path = "src/1_0/main.rs"
